v_name:
  type: string
  required: true
  regex: '^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}$'

v_id:
  type: integer
  required: true
  min: 100
  max: 999999999

v_clone_id:
  type: integer
  required: true
  min: 100
  max: 999999999

v_vlan:
  type: integer
  required: true
  min: 2
  max: 4094

v_host_username:
  type: string
  default: root
  required: false
  regex: '^[a-z_][a-z0-9_-]{0,31}$'

v_host_keyfile:
  type: string
  default: <Your PVE host ip goes here>
  required: false
  regex: '^/home/[a-z_][a-z0-9_-]{0,31}/\.ssh/.*$'
  # Path to the ssh keyfile used to access the Proxmox host

v_host_ip:
  type: string
  required: false
  default: 192.168.6.3
  regex: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
  # Validates IPv4 addresses like 192.168.1.100
  # Ensures each octet is between 0–255
  # Does not allow leading zeros like 01

v_cores:
  type: integer
  required: false
  default: 1
  min: 1
  max: 4

v_memory:
  type: integer
  required: false
  default: 2048
  min: 256
  max: 8192

v_disk:
  type: integer
  required: false
  default: 8
  min: 4
  max: 1024

v_driver:
  type: string
  required: false
  default: "virtio"
  # Full set of models Proxmox exposes
  regex: '^(e1000|e1000-82540em|e1000-82544gc|e1000-82545em|e1000e|i82551|i82557b|i82559er|ne2k_isa|ne2k_pci|pcnet|rtl8139|virtio|vmxnet3)$'

v_bridge:
  type: string
  required: false
  default: "vmbr0"
  # General Linux interface-name rule: start with a letter,
  # up to 15 chars total, allowed body chars are [A-Za-z0-9_.:-]
  regex: '^[A-Za-z][A-Za-z0-9_.:-]{0,14}$'

v_balloon:
  type: integer
  required: false
  default: 512
  min: 256
  max: 8192

v_boot_start:
  type: boolean
  required: false
  default: true

v_ci_upgrade:
  type: boolean
  required: false
  default: true

v_ci_username:
  type: string
  default: pch
  required: false
  regex: '^[a-z_][a-z0-9_-]{0,31}$'

v_ci_password:
  type: string
  required: false
  default: password
  minlength: 8
  regex: '^[\x20-\x7E]{8,128}$'
  # printable ASCII, no spaces -> change to [^\s] if spaces OK

v_change_pwd:
  type: boolean
  default: true
  required: false

v_ci_publickey:
  type: list
  required: false
  empty: True
  default:
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAILdNDjsqywS/4LcaCg35c+QE9V2vQ4VVfXsPVJVi6Dj6 nije-key'
    - 'ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIEnQDipaxA3UXONu83gW17HAsde/DtYeNxC+Uif9YcK ansible-automation'
  schema:
    type: string
    regex: '^(ssh-(rsa|dss|ed25519|ecdsa) [A-Za-z0-9+/=]+ ?[a-zA-Z0-9._-]+)?$'
    # Validates SSH public keys
    # Allows optional comment at the end

v_ci_domain:
  type: string
  default: pch.dk
  required: false
  regex: '^(?=.{1,253}$)([A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+[A-Za-z]{2,}$'


v_ci_dns_server:
  type: string
  required: false
  default: 192.168.9.5
  regex: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
  # Validates IPv4 addresses like 192.168.1.100
  # Ensures each octet is between 0–255
  # Does not allow leading zeros like 01

v_ci_ipaddress:
  type: string
  required: false
  regex: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
  # Validates IPv4 addresses like 192.168.1.100
  # Ensures each octet is between 0–255
  # Does not allow leading zeros like 01

v_ci_gateway:
  type: string
  required: false
  regex: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
  # Validates IPv4 addresses like 192.168.1.100
  # Ensures each octet is between 0–255
  # Does not allow leading zeros like 01

v_ci_netmask:
  type: string
  required: false
  regex: '^/(?:[0-9]|[12][0-9]|3[0-2])$'
  # Accepts /0–/32 (IPv4 CIDR).


v_ci_network:
  type: string
  default: "dhcp"
  required: false
  regex: '^(?i)(dhcp|static)$'

v_ip_prefix:
  type: string
  required: false
  default: "192.168"
  # two octets, optional trailing dot
  regex: '^(?:25[0-5]|2[0-4]\d|1?\d?\d)\.(?:25[0-5]|2[0-4]\d|1?\d?\d)\.?$'

# --------------------------- PROXMOX SSHD DEFAULTS ---------------------------
PermitRootLogin:
  type: string
  default: "without-password"
  required: false
  regex: "(?i)^(yes|no|without-password|forced-commands-only)$"

PasswordAuthentication:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

PermitEmptyPasswords:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

UseDNS:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

AllowTcpForwarding:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

X11Forwarding:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

ClientAliveInterval:
  type: integer
  default: 300
  required: false

ClientAliveCountMax:
  type: integer
  default: 2
  required: false

MaxAuthTries:
  type: integer
  default: 3
  required: false

MaxSessions:
  type: integer
  default: 2
  required: false

Compression:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no|delayed)$"

LogLevel:
  type: string
  default: "VERBOSE"
  required: false
  regex: "(?i)^(QUIET|FATAL|ERROR|INFO|VERBOSE|DEBUG|DEBUG1|DEBUG2|DEBUG3)$"

LoginGraceTime:
  type: integer
  default: 30
  required: false
  min: 1
  # only integers, expect it to be seconds

Subsystem:
  type: string
  default: "sftp /usr/lib/openssh/sftp-server"
  required: false
