host_username:
  type: string
  default: root
  required: false
  regex: '^[a-z_][a-z0-9_-]{0,31}$'
  # Max 32 characters
  # Lowercase only
  # No spaces
  # No uppercase letters
  # No special characters other than _ or -
  # Starts with a letter or _

host_ip:
  type: string
  required: true
  regex: '^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$'
  # Validates IPv4 addresses like 192.168.1.100
  # Ensures each octet is between 0–255
  # Does not allow leading zeros like 01

hostname:
  type: string
  required: true
  regex: '^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}$'
  # Max 63 characters
  # Starts with a letter or number
  # Contains only letters, numbers, and hyphens
  # Does not end with a hyphen

domain:
  type: string
  default: your.domain
  required: false
  regex: '^[a-zA-Z0-9][a-zA-Z0-9-]{0,62}\.[a-zA-Z]{2,}$'
  # Max 63 characters for the domain part
  # Starts with a letter or number
  # Contains only letters, numbers, and hyphens
  # Ends with a top-level domain (TLD) like .com, .org, etc.

sshkey_public:
  type: list
  required: false
  empty: True
  default:
    - 'public key'
    - 'public key'
  schema:
    type: string
    regex: '^(ssh-(rsa|dss|ed25519|ecdsa) [A-Za-z0-9+/=]+ ?[a-zA-Z0-9._-]+)?$'
    # Validates SSH public keys
    # Allows optional comment at the end

iso_urls:
  type: list
  required: false
  empty: True
  default:
    - 'https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.img'
    - 'https://releases.ubuntu.com/24.04/ubuntu-24.04.2-live-server-amd64.iso'
  schema:
    type: string
    regex: '^(https?|ftp)://[^\s/$.?#].[^\s]*$'
    # Validates URLs for ISO images
    # Allows http, https, and ftp protocols

iso_path:
  type: string
  required: false
  default: '/var/lib/vz/template/iso'
  regex: '^\/([a-zA-Z0-9._+-]+\/)*[a-zA-Z0-9._+-]+$'
  # Path to Promox ISO folder

host_change_pwd:
  type: boolean
  default: false
  required: false
  regex: '^(true|false)$'
  # Accepts true or false values

host_keyfile:
  type: string
  default: '/path/to/.ssh/keyfile'
  required: false
  regex: '^/home/[a-z_][a-z0-9_-]{0,31}/\.ssh/.*$'
  # Path to the ssh keyfile used to access the Proxmox host

host_reboot:
  type: boolean
  default: false
  required: false
  regex: '^(true|false)$'
  # Should Proxmox host reboot if required

host_file:
  type: string
  default: '/etc/hosts'
  required: false
  regex: '^\/([a-zA-Z0-9._+-]+\/)*[a-zA-Z0-9._+-]+$'
  # Path to the sshd config file on the Proxmox host

sshd_searchstring:
  type: string
  default: 'include'
  required: false
  regex: '^[^\n\r]{1,512}$'
  # Default search string 'include' used in sshd config

sshd_config_path:
  type: string
  default: '/etc/ssh/sshd_config'
  required: false
  regex: '^(/[^/\0]+)+/?$'
  # Default path to sshd_config

sshd_custom_config:
  type: string
  default: "/etc/ssh/sshd_config.d/99-custom.conf"
  required: false
  regex: '^(/[^/\0]+)+/?$'
  # Default path to desired sshd_config

# --------------------------- PROXMOX SSHD DEFAULTS ---------------------------
ssh_PermitRootLogin:
  type: string
  default: "without-password"
  required: false
  regex: "(?i)^(yes|no|without-password|forced-commands-only)$"

ssh_PasswordAuthentication:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

ssh_PermitEmptyPasswords:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

ssh_UseDNS:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

ssh_AllowTcpForwarding:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

ssh_X11Forwarding:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no)$"

ssh_ClientAliveInterval:
  type: integer
  default: 300
  required: false

ssh_ClientAliveCountMax:
  type: integer
  default: 2
  required: false

ssh_MaxAuthTries:
  type: integer
  default: 3
  required: false

ssh_MaxSessions:
  type: integer
  default: 2
  required: false

ssh_Compression:
  type: string
  default: "no"
  required: false
  regex: "(?i)^(yes|no|delayed)$"

ssh_LogLevel:
  type: string
  default: "VERBOSE"
  required: false
  regex: "(?i)^(QUIET|FATAL|ERROR|INFO|VERBOSE|DEBUG|DEBUG1|DEBUG2|DEBUG3)$"

ssh_LoginGraceTime:
  type: integer
  default: 30
  required: false
  min: 1
  # only integers, expect it to be seconds

ssh_Subsystem:
  type: string
  default: "sftp /usr/lib/openssh/sftp-server"
  required: false
